name: On Push Run

on: push

env:
  DAY_OF_WEEK: run-script-github-actions

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say Hello
      - uses: actions/checkout@env_var
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $Name_User ,do epic shit"
        env:
          Name_User: Lib
